"use client";

import React, { useMemo, useState } from "react";
import emailjs from "@emailjs/browser";
import { stateOptions } from "../../data/preIpoTools";

const emailServiceId = "service_kskk7az";
const emailTemplateId = "template_j7ir5zf";
const emailPublicKey = "pSlQYBFQMk4wsZrxw";

const initialToolState = {
  name: "",
  email: "",
  state: "CA",
  holderType: "",
  equityValue: "",
  costBasis: "",
  goals: [],
  immediatePct: 20,
  midPct: 40,
  dafPct: 10,
  taxStress: 3,
  timeline: 3,
  grants: [],
};

function parseMoney(value) {
  return Number(String(value || "").replace(/[^0-9.]/g, "")) || 0;
}

function formatMoney(value, compact = false) {
  const amount = Number.isFinite(value) ? value : 0;
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
    notation: compact && amount >= 1_000_000 ? "compact" : "standard",
  }).format(amount);
}

function clamp(value, min, max) {
  return Math.min(Math.max(value, min), max);
}

function calculateSnapshot(config, form) {
  const state = stateOptions.find((option) => option.code === form.state) || stateOptions[0];
  const equityValue = parseMoney(form.equityValue);
  const costBasis = parseMoney(form.costBasis);
  const gain = Math.max(0, equityValue - costBasis);
  const blendedTaxRate = config.assumptions.federalLongTermRate + state.rate;
  const estimatedTax = gain * blendedTaxRate;
  const immediateValue = equityValue * (form.immediatePct / 100);
  const midValue = equityValue * (form.midPct / 100);
  const longPct = Math.max(0, 100 - form.immediatePct - form.midPct);
  const longValue = equityValue * (longPct / 100);
  const directIndexAllocation = Math.min(
    equityValue * config.assumptions.directIndexAllocationRate,
    immediateValue + midValue
  );
  const directIndexLosses = directIndexAllocation * config.assumptions.directIndexLossRate;
  const directIndexBenefit = directIndexLosses * blendedTaxRate;
  const dafPct = clamp(Number(form.dafPct) || config.assumptions.dafDefaultRate, 0, 30);
  const dafAmount = equityValue * (dafPct / 100);
  const dafGain = Math.min(gain, dafAmount);
  const dafCapitalGainAvoided = dafGain * blendedTaxRate;
  const dafDeductionValue = dafAmount * config.assumptions.ordinaryIncomeRate;

  return {
    state,
    equityValue,
    costBasis,
    gain,
    blendedTaxRate,
    estimatedTax,
    immediateValue,
    midValue,
    longPct,
    longValue,
    directIndexAllocation,
    directIndexBenefit,
    dafPct,
    dafAmount,
    dafCapitalGainAvoided,
    dafDeductionValue,
  };
}

function getPriorities(config, form) {
  const goalStrategyIds = form.goals.map((goalId) => {
    const goal = config.goals.find((item) => item.id === goalId);
    return goal?.strategyId || goalId;
  });
  const priorityIds = [
    ...goalStrategyIds,
    form.holderType === "employee" || form.holderType === "both" ? "protection" : null,
    "tax",
    "diversify",
    "estate",
    "liquidity",
  ].filter(Boolean);
  const seen = new Set();

  return priorityIds
    .map((id) => config.strategies.find((strategy) => strategy.id === id))
    .filter(Boolean)
    .filter((strategy) => {
      if (seen.has(strategy.id)) return false;
      seen.add(strategy.id);
      return true;
    })
    .slice(0, 3);
}

function buildLeadMessage(config, form, calc, priorities) {
  const holder = config.holderTypes.find((type) => type.id === form.holderType);
  const goals = config.goals
    .filter((goal) => form.goals.includes(goal.id))
    .map((goal) => goal.title)
    .join(", ");

  return [
    `${config.name} completed.`,
    "",
    `Name: ${form.name}`,
    `Email: ${form.email}`,
    `State: ${calc.state.name}`,
    `Holder type: ${holder?.title || "Not provided"}`,
    `Estimated position: ${formatMoney(calc.equityValue)}`,
    `Estimated cost basis: ${form.costBasis ? formatMoney(calc.costBasis) : "Not provided"}`,
    `Estimated embedded gain: ${formatMoney(calc.gain)}`,
    `Estimated tax without planning: ${formatMoney(calc.estimatedTax)}`,
    `Holding plan: ${form.immediatePct}% immediate, ${form.midPct}% in 1-3 years, ${calc.longPct}% long term`,
    `Illustrative DAF scenario: ${calc.dafPct}% / ${formatMoney(calc.dafAmount)}`,
    `Goals: ${goals || "Not provided"}`,
    `Tax concern score: ${form.taxStress}/5`,
    `Timeline urgency score: ${form.timeline}/5`,
    `Priority moves: ${priorities.map((item) => item.title).join("; ")}`,
    "",
    "This message was generated by the website snapshot tool. Figures are illustrative and gross of fees.",
  ].join("\n");
}

function FieldError({ error }) {
  if (!error) return null;
  return <p className="preipo-field-error">{error}</p>;
}

export default function PreIpoSnapshotTool({ config }) {
  const [hasAcknowledged, setHasAcknowledged] = useState(false);
  const [disclosureReady, setDisclosureReady] = useState(false);
  const [step, setStep] = useState(1);
  const [form, setForm] = useState(initialToolState);
  const [errors, setErrors] = useState({});
  const [leadStatus, setLeadStatus] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const calc = useMemo(() => calculateSnapshot(config, form), [config, form]);
  const priorities = useMemo(() => getPriorities(config, form), [config, form]);

  const updateField = (field, value) => {
    setForm((current) => ({ ...current, [field]: value }));
    if (errors[field]) {
      setErrors((current) => {
        const next = { ...current };
        delete next[field];
        return next;
      });
    }
  };

  const validateStep = (targetStep = step) => {
    const nextErrors = {};

    if (targetStep === 1) {
      if (!form.name.trim()) nextErrors.name = "Enter your name.";
      if (!form.email.trim()) {
        nextErrors.email = "Enter your email address.";
      } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) {
        nextErrors.email = "Enter a valid email address.";
      }
      if (!form.state) nextErrors.state = "Select your state.";
    }

    if (targetStep === 2) {
      if (!form.holderType) nextErrors.holderType = "Select how you hold the position.";
      if (parseMoney(form.equityValue) <= 0) {
        nextErrors.equityValue = "Enter an estimated position value.";
      }
    }

    if (targetStep === 3 && form.goals.length === 0) {
      nextErrors.goals = "Select at least one planning goal.";
    }

    setErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  const goNext = () => {
    if (!validateStep(step)) return;
    setStep((current) => Math.min(4, current + 1));
    window.requestAnimationFrame(() => {
      document.getElementById("snapshot-tool")?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  const goBack = () => {
    setErrors({});
    setStep((current) => Math.max(1, current - 1));
  };

  const toggleGoal = (goalId) => {
    setForm((current) => {
      const hasGoal = current.goals.includes(goalId);
      return {
        ...current,
        goals: hasGoal
          ? current.goals.filter((id) => id !== goalId)
          : [...current.goals, goalId],
      };
    });
    if (errors.goals) {
      setErrors((current) => {
        const next = { ...current };
        delete next.goals;
        return next;
      });
    }
  };

  const adjustHolding = (field, delta) => {
    setForm((current) => {
      const immediate = field === "immediatePct"
        ? clamp(current.immediatePct + delta, 0, 100)
        : current.immediatePct;
      const mid = field === "midPct"
        ? clamp(current.midPct + delta, 0, 100)
        : current.midPct;

      if (immediate + mid > 100) {
        return field === "immediatePct"
          ? { ...current, immediatePct: immediate, midPct: Math.max(0, 100 - immediate) }
          : { ...current, immediatePct: Math.max(0, 100 - mid), midPct: mid };
      }

      return { ...current, immediatePct: immediate, midPct: mid };
    });
  };

  const addGrant = () => {
    setForm((current) => ({
      ...current,
      grants: [
        ...current.grants,
        { id: crypto.randomUUID(), type: config.grantTypes[0], shares: "", value: "" },
      ],
    }));
  };

  const updateGrant = (id, field, value) => {
    setForm((current) => ({
      ...current,
      grants: current.grants.map((grant) => (
        grant.id === id ? { ...grant, [field]: value } : grant
      )),
    }));
  };

  const removeGrant = (id) => {
    setForm((current) => ({
      ...current,
      grants: current.grants.filter((grant) => grant.id !== id),
    }));
  };

  const handleDisclosureScroll = (event) => {
    const element = event.currentTarget;
    const atBottom = element.scrollTop + element.clientHeight >= element.scrollHeight - 12;
    if (atBottom) setDisclosureReady(true);
  };

  const submitLead = (event) => {
    event.preventDefault();
    setIsSubmitting(true);
    setLeadStatus("");

    const message = buildLeadMessage(config, form, calc, priorities);
    const holder = config.holderTypes.find((type) => type.id === form.holderType);

    emailjs
      .send(
        emailServiceId,
        emailTemplateId,
        {
          name: form.name,
          email: form.email,
          phoneNumber: "",
          message,
          toolName: config.name,
          companyName: config.companyName,
          state: calc.state.name,
          holderType: holder?.title || "",
          equityValue: formatMoney(calc.equityValue),
          estimatedTax: formatMoney(calc.estimatedTax),
        },
        emailPublicKey
      )
      .then(
        () => {
          setLeadStatus("Thank you. Your snapshot request has been sent to Inflection.");
        },
        () => {
          setLeadStatus(`Something went wrong. Please email ${config.contactEmail} or call (415) 450-6556.`);
        }
      )
      .finally(() => setIsSubmitting(false));
  };

  return (
    <main className="preipo-page" id="main-content">
      <section className="preipo-hero" aria-labelledby="preipo-title">
        <div className="preipo-hero__copy">
          <p className="preipo-eyebrow">{config.eyebrow}</p>
          <h1 id="preipo-title">{config.name}</h1>
          <p>{config.hero}</p>
          <a className="preipo-primary-link" href={hasAcknowledged ? "#snapshot-tool" : "#snapshot-disclosure"}>
            {hasAcknowledged ? "Start snapshot" : "Review disclosure"}
          </a>
        </div>

        <div className="preipo-hero__visual">
          <img
            src={config.heroImage.src}
            srcSet={config.heroImage.srcSet}
            sizes={config.heroImage.sizes}
            width={config.heroImage.width}
            height={config.heroImage.height}
            alt={config.heroImage.alt}
            fetchPriority="high"
          />
          <div className="preipo-visual-card">
            <span>Position</span>
            <strong>{config.companyName}</strong>
            <small>Pre-liquidity planning</small>
          </div>
        </div>
      </section>

      <section className="preipo-context" aria-label={`${config.companyName} planning context`}>
        <p>{config.audience}</p>
        <p>{config.proof}</p>
      </section>

      {!hasAcknowledged ? (
        <section className="preipo-disclosure" id="snapshot-disclosure" aria-labelledby="disclosure-title">
          <div>
            <p className="preipo-eyebrow">Required acknowledgement</p>
            <h2 id="disclosure-title">Read before using the snapshot</h2>
            <p>
              This acknowledgement is required before the interactive snapshot appears.
              Scroll through the disclosure text to enable the continue button.
            </p>
          </div>
          <div className="preipo-disclosure__panel">
            <div className="preipo-disclosure__body" onScroll={handleDisclosureScroll} tabIndex={0}>
              {config.disclosure.map((item) => (
                <article key={item.heading}>
                  <h3>{item.heading}</h3>
                  <p>{item.body}</p>
                </article>
              ))}
            </div>
            <button
              className="preipo-button preipo-button--primary"
              type="button"
              disabled={!disclosureReady}
              onClick={() => {
                setHasAcknowledged(true);
                window.requestAnimationFrame(() => {
                  document.getElementById("snapshot-tool")?.scrollIntoView({ behavior: "smooth", block: "start" });
                });
              }}
            >
              I have read and agree
            </button>
          </div>
        </section>
      ) : (
        <section className="preipo-tool" id="snapshot-tool" aria-labelledby="snapshot-tool-title">
          <div className="preipo-tool__header">
            <div>
              <p className="preipo-eyebrow">Snapshot builder</p>
              <h2 id="snapshot-tool-title">Four steps to a planning picture</h2>
            </div>
            <ol className="preipo-stepper" aria-label="Snapshot steps">
              {[1, 2, 3, 4].map((item) => (
                <li key={item} className={step === item ? "is-active" : step > item ? "is-complete" : ""}>
                  {item}
                </li>
              ))}
            </ol>
          </div>

          {step === 1 && (
            <div className="preipo-panel">
              <div className="preipo-panel__intro">
                <h3>First, identify the planning household.</h3>
                <p>These fields let Inflection follow up with the right context if you request a call.</p>
              </div>
              <div className="preipo-form-grid">
                <label className="preipo-field">
                  <span>Name</span>
                  <input
                    value={form.name}
                    onChange={(event) => updateField("name", event.target.value)}
                    autoComplete="name"
                    aria-invalid={Boolean(errors.name)}
                  />
                  <FieldError error={errors.name} />
                </label>
                <label className="preipo-field">
                  <span>Email</span>
                  <input
                    type="email"
                    value={form.email}
                    onChange={(event) => updateField("email", event.target.value)}
                    autoComplete="email"
                    aria-invalid={Boolean(errors.email)}
                  />
                  <FieldError error={errors.email} />
                </label>
                <label className="preipo-field">
                  <span>State</span>
                  <select
                    value={form.state}
                    onChange={(event) => updateField("state", event.target.value)}
                    aria-invalid={Boolean(errors.state)}
                  >
                    {stateOptions.map((option) => (
                      <option key={option.code} value={option.code}>
                        {option.name}
                      </option>
                    ))}
                  </select>
                  <FieldError error={errors.state} />
                </label>
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="preipo-panel">
              <div className="preipo-panel__intro">
                <h3>How do you hold {config.companyName}?</h3>
                <p>Round numbers are enough. The output is a planning snapshot, not a formal proposal.</p>
              </div>
              <div className="preipo-choice-grid" role="group" aria-label="Holder type">
                {config.holderTypes.map((type) => (
                  <button
                    key={type.id}
                    type="button"
                    className={form.holderType === type.id ? "preipo-choice is-selected" : "preipo-choice"}
                    onClick={() => updateField("holderType", type.id)}
                    aria-pressed={form.holderType === type.id}
                  >
                    <strong>{type.title}</strong>
                    <span>{type.label}</span>
                    <small>{type.note}</small>
                  </button>
                ))}
              </div>
              <FieldError error={errors.holderType} />

              <div className="preipo-form-grid">
                <label className="preipo-field">
                  <span>Estimated {config.companyName} position value</span>
                  <input
                    inputMode="decimal"
                    value={form.equityValue}
                    onChange={(event) => updateField("equityValue", event.target.value)}
                    placeholder="$5,000,000"
                    aria-invalid={Boolean(errors.equityValue)}
                  />
                  <FieldError error={errors.equityValue} />
                </label>
                <label className="preipo-field">
                  <span>Estimated cost basis</span>
                  <input
                    inputMode="decimal"
                    value={form.costBasis}
                    onChange={(event) => updateField("costBasis", event.target.value)}
                    placeholder="$0 or unknown"
                  />
                </label>
              </div>

              <div className="preipo-grants">
                <div>
                  <h4>Optional grant or lot details</h4>
                  <p>Use this for context only. Documents are not uploaded in this version.</p>
                </div>
                {form.grants.map((grant) => (
                  <div className="preipo-grant-row" key={grant.id}>
                    <select value={grant.type} onChange={(event) => updateGrant(grant.id, "type", event.target.value)}>
                      {config.grantTypes.map((type) => (
                        <option key={type}>{type}</option>
                      ))}
                    </select>
                    <input
                      value={grant.shares}
                      onChange={(event) => updateGrant(grant.id, "shares", event.target.value)}
                      placeholder="Shares"
                      inputMode="numeric"
                    />
                    <input
                      value={grant.value}
                      onChange={(event) => updateGrant(grant.id, "value", event.target.value)}
                      placeholder="Value"
                      inputMode="decimal"
                    />
                    <button type="button" onClick={() => removeGrant(grant.id)}>
                      Remove
                    </button>
                  </div>
                ))}
                <button className="preipo-button preipo-button--ghost" type="button" onClick={addGrant}>
                  Add grant or lot
                </button>
              </div>
            </div>
          )}

          {step === 3 && (
            <div className="preipo-panel">
              <div className="preipo-panel__intro">
                <h3>Choose the planning goals.</h3>
                <p>The snapshot prioritizes strategies around your selected goals and timing preferences.</p>
              </div>
              <div className="preipo-goal-grid" role="group" aria-label="Planning goals">
                {config.goals.map((goal) => (
                  <button
                    key={goal.id}
                    type="button"
                    className={form.goals.includes(goal.id) ? "preipo-goal is-selected" : "preipo-goal"}
                    onClick={() => toggleGoal(goal.id)}
                    aria-pressed={form.goals.includes(goal.id)}
                  >
                    <strong>{goal.title}</strong>
                    <span>{goal.body}</span>
                  </button>
                ))}
              </div>
              <FieldError error={errors.goals} />

              <div className="preipo-hold-plan">
                <h4>How much would you consider monetizing?</h4>
                <div className="preipo-hold-row">
                  <span>Immediate window</span>
                  <div>
                    <button type="button" onClick={() => adjustHolding("immediatePct", -5)}>-</button>
                    <strong>{form.immediatePct}%</strong>
                    <button type="button" onClick={() => adjustHolding("immediatePct", 5)}>+</button>
                  </div>
                </div>
                <div className="preipo-hold-row">
                  <span>One to three years</span>
                  <div>
                    <button type="button" onClick={() => adjustHolding("midPct", -5)}>-</button>
                    <strong>{form.midPct}%</strong>
                    <button type="button" onClick={() => adjustHolding("midPct", 5)}>+</button>
                  </div>
                </div>
                <div className="preipo-hold-row">
                  <span>Hold long term</span>
                  <strong>{calc.longPct}%</strong>
                </div>
              </div>

              <div className="preipo-slider-grid">
                <label>
                  <span>Tax concern</span>
                  <input
                    type="range"
                    min="1"
                    max="5"
                    value={form.taxStress}
                    onChange={(event) => updateField("taxStress", Number(event.target.value))}
                  />
                  <small>{form.taxStress}/5</small>
                </label>
                <label>
                  <span>Timeline urgency</span>
                  <input
                    type="range"
                    min="1"
                    max="5"
                    value={form.timeline}
                    onChange={(event) => updateField("timeline", Number(event.target.value))}
                  />
                  <small>{form.timeline}/5</small>
                </label>
              </div>
            </div>
          )}

          {step === 4 && (
            <div className="preipo-result" aria-live="polite">
              <div className="preipo-result__hero">
                <p className="preipo-eyebrow">Illustrative snapshot</p>
                <h3>{form.name.split(" ")[0] || "Your"} {config.companyName} planning picture</h3>
                <p>
                  Based on a {formatMoney(calc.equityValue, true)} position, estimated embedded gain of{" "}
                  {formatMoney(calc.gain, true)}, and a {Math.round(calc.blendedTaxRate * 1000) / 10}% blended
                  long-term capital gains assumption for {calc.state.name}.
                </p>
              </div>

              <div className="preipo-metrics">
                <article>
                  <span>Estimated gain</span>
                  <strong>{formatMoney(calc.gain, true)}</strong>
                </article>
                <article>
                  <span>Tax without planning</span>
                  <strong>{formatMoney(calc.estimatedTax, true)}</strong>
                </article>
                <article>
                  <span>Immediate liquidity bucket</span>
                  <strong>{formatMoney(calc.immediateValue, true)}</strong>
                </article>
                <article>
                  <span>Tax-loss offset scenario</span>
                  <strong>{formatMoney(calc.directIndexBenefit, true)}</strong>
                </article>
              </div>

              <section className="preipo-result-section">
                <h4>Your three priority moves</h4>
                <div className="preipo-priority-list">
                  {priorities.map((strategy, index) => (
                    <article key={strategy.id}>
                      <span>{String(index + 1).padStart(2, "0")}</span>
                      <div>
                        <p>{strategy.tag}</p>
                        <h5>{strategy.title}</h5>
                        <p>{strategy.body}</p>
                      </div>
                    </article>
                  ))}
                </div>
              </section>

              <section className="preipo-result-section preipo-daf">
                <div>
                  <p className="preipo-eyebrow">Charitable planning</p>
                  <h4>DAF contribution scenario</h4>
                  <p>
                    A {calc.dafPct}% appreciated-share contribution equals {formatMoney(calc.dafAmount, true)}. In this
                    simplified illustration, it may avoid {formatMoney(calc.dafCapitalGainAvoided, true)} of
                    capital-gains tax and create an estimated {formatMoney(calc.dafDeductionValue, true)} income-tax
                    deduction value, subject to AGI limits and tax-adviser review.
                  </p>
                </div>
                <label>
                  <span>Contribution scenario</span>
                  <input
                    type="range"
                    min="0"
                    max="30"
                    step="1"
                    value={calc.dafPct}
                    onChange={(event) => updateField("dafPct", Number(event.target.value))}
                  />
                  <small>{calc.dafPct}% of estimated position value</small>
                </label>
              </section>

              <form className="preipo-result-cta" onSubmit={submitLead}>
                <div>
                  <h4>Turn this into a real plan.</h4>
                  <p>
                    Send the snapshot context to Inflection and schedule a 30-minute discovery call. Supporting
                    statements can be discussed after contact through an appropriate secure channel.
                  </p>
                </div>
                <div className="preipo-result-cta__actions">
                  <button className="preipo-button preipo-button--primary" type="submit" disabled={isSubmitting}>
                    {isSubmitting ? "Sending" : "Send snapshot request"}
                  </button>
                  <button className="preipo-button preipo-button--ghost" type="button" onClick={() => window.print()}>
                    Print or save
                  </button>
                </div>
                {leadStatus && <p className="preipo-status" role="status">{leadStatus}</p>}
              </form>

              <section className="preipo-disclaimer" aria-label="Important disclosures">
                <h4>Important disclosures</h4>
                <p>
                  This snapshot is educational and illustrative. It is not investment, legal, tax, or accounting
                  advice. Figures are hypothetical, gross of fees, and depend on user inputs, market conditions,
                  financing costs, adviser review, and individual circumstances. Inflection may have a financial
                  interest in acquiring clients through this tool.
                </p>
              </section>
            </div>
          )}

          <div className="preipo-tool__nav">
            {step > 1 && (
              <button className="preipo-button preipo-button--ghost" type="button" onClick={goBack}>
                Back
              </button>
            )}
            {step < 4 && (
              <button className="preipo-button preipo-button--primary" type="button" onClick={goNext}>
                {step === 3 ? "See snapshot" : "Continue"}
              </button>
            )}
          </div>
        </section>
      )}
    </main>
  );
}
